### ISSUE TITLE
NotImplementedError: Verification code required

### ISSUE THREAD

**Issue by kashuorg** [iambus/xunlei-lixian#448]
第一次用这软件，可惜用不了……   : (
所用系统：Xubuntu 14.04.3 LTS amd64

python lixian_cli.py login 
ID: XXXXXX
Password: 
Saving login session to /home/kashu/.xunlei.lixian.cookies
Traceback (most recent call last):
  File "lixian_cli.py", line 63, in <module>
    execute_command()
  File "lixian_cli.py", line 60, in execute_command
    commands[command](args[1:])
  File "/tmp/xunlei-lixian-master/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, *args, **kwargs))
  File "/tmp/xunlei-lixian-master/lixian_commands/login.py", line 42, in login
    XunleiClient(args.username, args.password, args.cookies, login=True, verification_code_reader=verification_code_reader)
  File "/tmp/xunlei-lixian-master/lixian.py", line 229, in __init__
    self.login()
  File "/tmp/xunlei-lixian-master/lixian.py", line 385, in login
    verification_code = self.read_verification_code()
  File "/tmp/xunlei-lixian-master/lixian.py", line 359, in read_verification_code
    raise NotImplementedError('Verification code required')
NotImplementedError: Verification code required

**Comment by xie-dongping** [comment]
这和你的帐号有关。用Web界面登录一下，输入一下验证码一般就可以了。

否则就要写OCR代码了...

**Comment by linux0ne** [comment]
@xie-dongping 我也遇到了这个问题，我在web端登陆的时候，也没有遇到提示输入验证码的情况呀。这个OCR代码不会写，有什么具体的思路没？
