### ISSUE TITLE
用不了，报错，请帮忙看看

### ISSUE THREAD

**Issue by zhangsl16** [iambus/xunlei-lixian#449]
ShuanglongdeMacBook-Pro:xunlei-lixian zhangsl16$ ./lixian_cli.py list
Traceback (most recent call last):
  File "./lixian_cli.py", line 63, in <module>
    execute_command()
  File "./lixian_cli.py", line 60, in execute_command
    commands[command](args[1:])
  File "/Users/zhangsl16/xunlei-lixian/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, *args, **kwargs))
  File "/Users/zhangsl16/xunlei-lixian/lixian_commands/list.py", line 50, in list_task
    tasks = lixian_query.search_tasks(client, args)
  File "/Users/zhangsl16/xunlei-lixian/lixian_query.py", line 439, in search_tasks
    base.query_search()
  File "/Users/zhangsl16/xunlei-lixian/lixian_query.py", line 161, in query_search
    self.download_jobs += query.query_search()
  File "/Users/zhangsl16/xunlei-lixian/lixian.py", line 193, in __len__
    self.touch()
  File "/Users/zhangsl16/xunlei-lixian/lixian.py", line 117, in touch
    self.hit_page(0)
  File "/Users/zhangsl16/xunlei-lixian/lixian.py", line 122, in hit_page
    info = self.fetch_page(page, self.page_size)
  File "/Users/zhangsl16/xunlei-lixian/lixian.py", line 491, in <lambda>
    fetch_page = lambda page_index, page_size: self.read_task_page_info_by_page_index(type_id, page_index, page_size)
  File "/Users/zhangsl16/xunlei-lixian/lixian.py", line 449, in read_task_page_info_by_page_index
    return self.read_task_page_info_by_url(self.to_page_url(type_id, page_index, page_size))
  File "/Users/zhangsl16/xunlei-lixian/lixian.py", line 22, in withretry
    return f(*args, **kwargs)
  File "/Users/zhangsl16/xunlei-lixian/lixian.py", line 434, in read_task_page_info_by_url
    data = parse_json_response(page)
  File "/Users/zhangsl16/xunlei-lixian/lixian.py", line 891, in parse_json_response
    raise RuntimeError('Invalid response')
RuntimeError: Invalid response

**Comment by sinofool** [comment]
同样的问题，返回的是迅雷首页的HTML代码。看来是改了接口。

**Comment by sinofool** [comment]
同一个地址dynamic.cloud.vip.xunlei.com根据不同来源IP返回了不同的功能，看来是屏蔽了一部分国外的IP提示只为国内用户服务。但是有一些误判。
找了个不同的代理暂时绕过了。
