### ISSUE TITLE
下载美剧遇到问题

### ISSUE THREAD

**Issue by mytts** [iambus/xunlei-lixian#450]
lx download 'ed2k://|file|Black.Sails.S03E08.720p.HDTV.x264-FLEET.mkv|1190580710|B08DDF1BC86F64471665F134E5A8A23D|h=CMRG32YOI5B7TI656CANYHPW7JESG6VS|/'
Traceback (most recent call last):
  File "/usr/bin/lx", line 63, in <module>
    execute_command()
  File "/usr/bin/lx", line 60, in execute_command
    commands[command](args[1:])
  File "/usr/share/xunlei-lixian/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, *args, **kwargs))
  File "/usr/share/xunlei-lixian/lixian_commands/download.py", line 282, in download_task
    query.query_once()
  File "/usr/share/xunlei-lixian/lixian_query.py", line 152, in query_once
    self.prepare()
  File "/usr/share/xunlei-lixian/lixian_query.py", line 137, in prepare
    self.commit()
  File "/usr/share/xunlei-lixian/lixian_query.py", line 115, in commit
    self.client.add_batch_tasks(map(lixian_encoding.try_native_to_utf_8, urls))
  File "/usr/share/xunlei-lixian/lixian.py", line 700, in add_batch_tasks
    assert not msg, repr(msg.decode('utf-8'))
AssertionError: u'\u8be5\u8d44\u6e90\u88ab\u4e3e\u62a5\uff0c\u65e0\u6cd5\u6dfb\u52a0\u5230\u79bb\u7ebf\u7a7a\u95f4[0975]'

**Comment by mytts** [comment]
看了一下刚才的unicode的字符串 

是 '该资源被举报，无法添加到离线空间[0975]'
