### ISSUE TITLE
2016年3月以来持续报错：NotImplementedError: Verification code required

### ISSUE THREAD

**Issue by linux0ne** [iambus/xunlei-lixian#451]
Saving login session to .xunlei.lixian.cookies
Traceback (most recent call last):
  File "/opt/xunlei-lixian/lixian_cli.py", line 63, in <module>
    execute_command()
  File "/opt/xunlei-lixian/lixian_cli.py", line 60, in execute_command
    commands[command](args[1:])
  File "/opt/xunlei-lixian/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, *args, **kwargs))
  File "/opt/xunlei-lixian/lixian_commands/login.py", line 42, in login
    XunleiClient(args.username, args.password, args.cookies, login=True, verification_code_reader=verification_code_reader)
  File "/opt/xunlei-lixian/lixian.py", line 229, in __init__
    self.login()
  File "/opt/xunlei-lixian/lixian.py", line 385, in login
    verification_code = self.read_verification_code()
  File "/opt/xunlei-lixian/lixian.py", line 359, in read_verification_code
    raise NotImplementedError('Verification code required')
NotImplementedError: Verification code required

**Comment by linux0ne** [comment]
改用下面的命令来登陆：
lx login --verification-code-path=/home/o/login.jpg
ID: ××××××××××
Password: 
Saving login session to .xunlei.lixian.cookies
Verification code picture is saved to /home/o/login.jpg, please open it manually and enter what you see.
Verification code: GdVZ   -----------------------------------------------------》 在这里输入了验证码
Traceback (most recent call last):
  File "/opt/xunlei-lixian/lixian_cli.py", line 63, in <module>
    execute_command()
  File "/opt/xunlei-lixian/lixian_cli.py", line 60, in execute_command
    commands[command](args[1:])
  File "/opt/xunlei-lixian/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, *args, **kwargs))
  File "/opt/xunlei-lixian/lixian_commands/login.py", line 42, in login
    XunleiClient(args.username, args.password, args.cookies, login=True, verification_code_reader=verification_code_reader)
  File "/opt/xunlei-lixian/lixian.py", line 229, in __init__
    self.login()
  File "/opt/xunlei-lixian/lixian.py", line 399, in login
    raise RuntimeError('login failed')
RuntimeError: login failed
======================================================

结果如上，依然失败。

PS:
1、这里用了命令我才看到了验证码，而我在web端登陆lixian.xunlei.com网址的时候，从来都没有要求输入过验证码，哪怕是命令行登陆lixian的时候提示说是验证码的问题。

**Comment by linux0ne** [comment]
依然没有解决    得从源码开始研究了？？

**Comment by 4ft35t** [comment]
可以用导入 cookie 的方式解决登录问题
https://gist.githubusercontent.com/4ft35t/96bb57be2cda041e6ba5c35dc0034937/raw/05710627cf7332132173340cee7e658d84f499e4/cookie_convert.py
