### ISSUE TITLE
经典的login failed问题再显不已

### ISSUE THREAD

**Issue by linux0ne** [iambus/xunlei-lixian#457]
o@o-Linux:~$ lx login xxxxxxxx -
Password: 
Saving login session to .xunlei.lixian.cookies
Traceback (most recent call last):
  File "/opt/xunlei-lixian/lixian_cli.py", line 63, in <module>
    execute_command()
  File "/opt/xunlei-lixian/lixian_cli.py", line 60, in execute_command
    commands[command](args[1:])
  File "/opt/xunlei-lixian/lixian_cli_parser.py", line 165, in parse
    return f(parser(args_list, *args, **kwargs))
  File "/opt/xunlei-lixian/lixian_commands/login.py", line 42, in login
    XunleiClient(args.username, args.password, args.cookies, login=True, verification_code_reader=verification_code_reader)
  File "/opt/xunlei-lixian/lixian.py", line 229, in __init__
    self.login()
  File "/opt/xunlei-lixian/lixian.py", line 399, in login
    raise RuntimeError('login failed')
RuntimeError: login failed

------------------------------------分割线----------------------------------

经典问题再现，有没有解决的方式 ，大家说一下思路，项目没有接手，可能是因为太浩大了，但是具体的小问题的解决思路还是请大家多多关注 。

**Comment by chainone** [comment]
我也碰到这个问题了

**Comment by 4ft35t** [comment]
用导入 cookie 的方式解决
https://gist.githubusercontent.com/4ft35t/96bb57be2cda041e6ba5c35dc0034937/raw/05710627cf7332132173340cee7e658d84f499e4/cookie_convert.py

**Comment by linux0ne** [comment]
@4ft35t   谢谢，很感谢。
我试一下
